name: Build and Deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Install and Build 🔧
      run: |
        npm install
        npm run build
    - name: Copy index file to dist folder
      uses: canastro/copy-file-action@master
      with:
        source: "public/index.html"
        target: "public/dist/index.html"
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: public/dist
